[package]
name = "afl-fuzz-frontend"
version = "0.3.2"
authors = ["Leander Tentrup <tentrup@react.uni-saarland.de>"]
edition = "2018"

[dependencies]
afl = "0.4"
rtlola-frontend = {path = "../frontend/"}

[workspace]
